resources:
- manager.yaml
- controller-namespace.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: registry.redhat.io/codeready-workspaces/crw-2-rhel8-operator:latest
  newName: quay.io/eclipse/codeready-operator
  newTag: next
