apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: system
spec:
  replicas: 1
  template:
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: $(CONTROLLER_SERVICE_ACCOUNT)
      containers:
        - name: devworkspace-controller
          image: quay.io/devfile/devworkspace-controller:next
          ports:
            - name: liveness-port
              containerPort: 6789
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: liveness-port
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: liveness-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          args:
            - /usr/local/bin/devworkspace-controller
            - --enable-leader-election
          resources:
            limits:
              cpu: 200m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 20Mi
          env:
            - name: CONTROLLER_SERVICE_ACCOUNT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: OPERATOR_NAME
              value: devworkspace-operator
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RELATED_IMAGE_devworkspace_webhook_server
              value: registry.redhat.io/codeready-workspaces/devworkspace-controller-rhel8:2.8
            - name: RELATED_IMAGE_pvc_cleanup_job
              value: registry.redhat.io/ubi8/ubi-minimal:8.3
            - name: WATCH_NAMESPACE
              value: ''
